### ISSUE TITLE
Tarball missing pll-modules files

### ISSUE THREAD

**Issue by brantfaircloth** [ddarriba/modeltest#22]
Good afternoon, 

I was following the instructions for building modeltest-ng using cmake from the tarball, but it seems the tarball does not include the necessary files in `pll-modules`.  The specific error during the build is:

```
[  3%] Generating ../localdeps/lib/libpll.a
/bin/sh: /home/brant/src/modeltest-0.1.5/libs/pll-modules/install-with-libpll.sh: No such file or directory
make[2]: *** [localdeps/lib/libpll.a] Error 127
make[1]: *** [libs/CMakeFiles/libpll.dir/all] Error 2
make: *** [all] Error 2
```
Checking out the source (and submodules) fixes the issue, but this does not seem to be the expected behavior of a build from the tarball (as far as I can tell).

**Comment by ddarriba** [comment]
I see different errors here.

brantfaircloth: Is it possible that you downloaded the wrong tarball? You should use the link below "Sources" section instead of "Assets". Time ago, the autogenerated zip/tarball was located below the release description, but now I don't know why it shows up at the top.

justincbagley: It seems that you don't have avx extensions and thus you cannot compile libpll. I'll try to find a solution ASAP.
